// ignore_for_file: prefer_interpolation_to_compose_strings

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart' as pathProvider;
import 'package:path/path.dart' as pathI;

class ImageInput extends StatefulWidget {
  final Function seImage;

  ImageInput(this.seImage);

  @override
  State<ImageInput> createState() => _ImageInputState();
}

class _ImageInputState extends State<ImageInput> {
  File? _imageLoad;

  Future<void> takePicture() async {
    //the 'imageFile' is a path inside quatation with the image name generated by the camera
    final imageFile = await ImagePicker.pickImage(
      source: ImageSource.camera,
      maxWidth: 600,
    );
    if (imageFile == null) {
      return;
    }
    setState(() {
      _imageLoad = imageFile;
    });
    //device storage file selection
    final appDir = await pathProvider.getApplicationDocumentsDirectory();
    //imageFile.path is imagefile with out quatation marks
    final fileName = pathI.basename(imageFile.path);

    final savedImage = await imageFile.copy('${appDir.path}/$fileName');
    //pass the saved image to the function
    widget.seImage(savedImage);
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        const SizedBox(
          height: 12,
        ),
        Container(
          decoration: BoxDecoration(
            border: Border.all(
              width: 2,
              color: Colors.grey,
            ),
            borderRadius: const BorderRadius.all(
              Radius.circular(9),
            ),
          ),
          alignment: Alignment.center,
          height: 150,
          width: 150,
          child: _imageLoad != null
              ? Image.file(
                  _imageLoad!,
                  fit: BoxFit.cover,
                  width: double.infinity,
                )
              : const Text(
                  'no image taken',
                  textAlign: TextAlign.center,
                ),
        ),
        const SizedBox(
          width: 12,
        ),
        Expanded(
          child: Container(
            width: 100,
            height: 100,
            decoration: BoxDecoration(
              borderRadius: const BorderRadius.all(
                Radius.circular(9),
              ),
              color: Colors.grey[300],
            ),
            child: TextButton.icon(
              onPressed: takePicture,
              label: const Text(
                'take picture',
                textAlign: TextAlign.center,
              ),
              icon: const Icon(Icons.camera),
            ),
          ),
        )
      ],
    );
  }
}
